### ISSUE TITLE
Статистика скорости операций

### ISSUE THREAD

**Issue by SergiySPB** [antoncst/gamma#3]
Для совершенствования алгоритма требуется статистика операций, а именно:

1. Время на первую  и последнюю операцию XOR1 + XOR3 (без матрицы) но с РСЛОС;
2. Время на первую  и последнюю операцию XOR1 + XOR3 (без матрицы) но БЕЗ РСЛОС;
3. Время только на матрицу БЕЗ  XOR1 + XOR3 и БЕЗ РСЛОС;

**Comment by antoncst** [comment]
То есть я выкладываю три разных версии на хаб, а ты сделаешь замеры. Кстати по поводу замеров, ну не мерь ты секундомером, он ведь сам пишет время. Да, вспомнил, сперва сделаю чтобы он выводил время при decrypt, как ты просил, хотя и время encrypt и decrypt должны совпадать.

**Comment by SergiySPB** [comment]
Статистика собрана
