### ISSUE TITLE
Решенияюе проблемы диффузии

### ISSUE THREAD

**Issue by SergiySPB** [antoncst/gamma#8]
Предложить варианты доработки алгоритма для удовлетворения проблем диффузии по примеру определению Шнаера.

**Comment by SergiySPB** [comment]
Вариант 1.1
После первого XOR'a включить итерацию LSFR, тогда последовательность итераций на одном блоке будет такова XOR->LFSR->PMA-XOR

**Comment by antoncst** [comment]
Вопросы:
1. Ещё один LFSR замедлит и так не быстрый алгоритм (на сколько?).
2. Трудозатраты на реализацию обратного РСЛОС (LFSR) для decrypt.

**Comment by antoncst** [comment]
По первым моим прикидкам, на первой итерации Вариант 1.1 приведёт к незначительной диффузии.

**Comment by antoncst** [comment]
Вариант 2.1
1. R1' = R1 XOR  S1
2. R1'' = F( R1')
Где S1 - первый блок входных данных
R1 - random
F - функция: РСЛОС или Преоб45, преобразовние осуществляется в цикле достаточное количество раз, для полного изменения R1.
Далее по нашему алгоритму.
Тогда 
а) уже на первой итерации изменение одного бита S приведёт к полному изменению выходного блока данных.
б) не повлияет на скорость

**Comment by antoncst** [comment]
Создан и реализован алгоритм диффузии. Он же применяется для конфузии.
